### ISSUE TITLE
PeskaVLP

### ISSUE THREAD

**Issue by fallcat** [CAMMA-public/SurgVLP#2]
Hi!

Great work!
I saw that you also made PeskaVLP. Do you plan to release the model and/or pipeline?

Thank you!

Best,
Weiqiu

**Comment by Flaick** [comment]
Hey, thank you for the interest! We will push the weight soon and the code will be released in the other repo, maybe in a few weeks.

**Comment by fallcat** [comment]
Thank you! Great work!
