### ISSUE TITLE
Could you please help me to solve this error?

### ISSUE THREAD

**Issue by cascat0** [CAMMA-public/SurgVLP#7]
(surgvlp) PS D:\SurgVLP-main> python D:\SurgVLP-main\demo.py
Traceback (most recent call last):
  File "D:\SurgVLP-main\demo.py", line 10, in <module>
    model, preprocess = surgvlp.load(configs.model_config, device=device)
  File "D:\SurgVLP-main\surgvlp\surgvlp.py", line 142, in load
    model_path = _download(_MODELS, model_name, download_root or os.path.expanduser("~/.cache/surgvlp"))
  File "D:\SurgVLP-main\surgvlp\surgvlp.py", line 124, in _download
    result = subprocess.run(command, capture_output=True, text=True)
  File "C:\Users\dell\anaconda3\envs\surgvlp\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\dell\anaconda3\envs\surgvlp\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\dell\anaconda3\envs\surgvlp\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by Flaick** [comment]
hello，sorry we do not support downloading model weights with window system, you can follow these steps to load the model:
1. download model weights by copy pasting the link:
_MODELS = {
    "SurgVLP": "https://seafile.unistra.fr/f/93757ace1bfc47248e1e/?dl=1",
    "HecVL": "https://seafile.unistra.fr/f/3b9b9207068a4b03bc2a/?dl=1",
    "PeskaVLP": "https://seafile.unistra.fr/f/65a2b1bf113e428280d0/?dl=1",
} to web browser.
2. Use surgvlp.load(config, pretrain='...pth') to load the model

**Comment by Flaick** [comment]
yeah, to solve that, you will need to download the source file and build the model locally. First, manage to download the hugging face config and weights file from the website, then set the file directory to the files
